### PR TITLE
Adding Daemon Option

### PR DESCRIPTION
**Pull request by nicomartinezdev**
- Addresses Issue #9.
- Adding 'd' 'daemon' flag to run kpoof as a daemon.
- Daemon output is redirected to a local file named 'kpoof-output.txt'

### CODE REVIEW

**Review by lypht — CHANGES_REQUESTED** [review]
Two items, of unequal importance.  
1) Without the -d flag (master, currently) the user has a reminder that kpoof is running by holding the shell in the foreground.  But it's easy to daemonize more than once without remembering to manually killing the process once done.  This can be catastrophic if these processes are forgotten, and left to run, and potentially collide or conflict.  We need to be able to implement an idler, or better, a single daemon limiter.
2) We can merge once the asciinema is updated with the `-d` flag

**Comment by scottrigby** [comment]
Added a commit - note this should not be merged as-is, per the commit message. But does work, with the caveat that it supports only one port-forward operation at a time. In the commit message I also noted a way we could address that issue though.

**Comment by scottrigby** [comment]
@here No rush, but pushing some work I did earlier Today where I added what appears to be a working version of the daemon, independent `--killd` option commands, and a `--killd-all` option as well to nuke all running kpoof daemons.

One note: the way kpoof is written now will not check for existing port-forwarding sessions, so if you for example have `50080:80` already forwarding, and then try to also port-forward 80 in another pod, you will already get a conflict. This PR would continue to work if we updated kpoof to set a different local port (increment etc) if there's already another pf session using it. That can be a separate feature though if we want to support that.

**Comment by scottrigby** [comment]
Oh this also makes the logfile more in line with existing standards (separate files per session, dated, etc). And uses a path based on the current user running the command (`$HOME/.kpoof`).

**Comment by scottrigby** [comment]
Slack test

**Comment by scottrigby** [comment]
Slack test

**Comment by scottrigby** [comment]
@lypht PS lmk when you get a chance to test this, and also let's think about the 2nd part of this comment as a potential new feature? https://github.com/farmotive/kpoof/pull/10#issuecomment-386126802

**Comment by lypht** [comment]
No longer working for me on first pass:
```$ ./kpf
Namespace? (default heptio-contour):
     1	basekamp
     2	cert-manager
     3	default
     4	heptio-contour
     5	kube-public
     6	kube-system
     7	lypht
     8	paw
     9	r6by
    10	whereapy
1
Pod number? (default 1):
     1	basekamp-html-2009-555231067-scbph
     2	basekamp-reduce-drupal-b5569b748-jxhrr
     3	basekamp-reduce-mariadb-6755958cc-xf8jr
1
error: at least 1 PORT is required for port-forward
See 'kubectl port-forward -h' for help and examples.```

**Comment by scottrigby** [comment]
@lypht It's the example you used. Try pod 2. That error also happens with version `2.0.2`

**Comment by scottrigby** [comment]
@lypht just added observability while daemonizing, with a friendly reminder to stop the process. Check it out?

**Comment by scottrigby** [comment]
PS I addressed the new issue I noted in https://github.com/farmotive/kpoof/pull/10#issuecomment-386126802 above with an independent PR #12.

**Pull request merged**
