### PR TITLE
Allow multiple kpoof sessions to the same k8s port

### PR DESCRIPTION
**Pull request by scottrigby**
This PR changes from adding 50000 to dynamic port binding, in order to support multiple kpoof connections to different apps on the same k8s port.

Right now, if you wanted to port-forward to two different pods using port 443/80 with kpoof, on the second pod you'd get:
```
Unable to listen on port 50443: All listeners failed to create with the following errors: Unable to create listener: Error listen tcp4 127.0.0.1:50443: bind: address already in use, Unable to create listener: Error listen tcp6 [::1]:50443: bind: address already in use
Unable to listen on port 50080: All listeners failed to create with the following errors: Unable to create listener: Error listen tcp4 127.0.0.1:50080: bind: address already in use, Unable to create listener: Error listen tcp6 [::1]:50080: bind: address already in use
error: Unable to listen on any of the requested ports: [{50443 443} {50080 80}]
```

With this patch, all is well in the port-forwarding universe:

Pod 1:
```
Forwarding from 127.0.0.1:61903 -> 443
Forwarding from [::1]:61903 -> 443
Forwarding from 127.0.0.1:61904 -> 80
Forwarding from [::1]:61904 -> 80
```

Pod 2:
```
Forwarding from 127.0.0.1:61941 -> 443
Forwarding from [::1]:61941 -> 443
Forwarding from 127.0.0.1:61942 -> 80
Forwarding from [::1]:61942 -> 80
```

### CODE REVIEW

**Comment by scottrigby** [comment]
PS, if there's a reason why we don't want to use dynamic binding for port forwarding, let's talk about that. There are other ways to handle this - for example, we could alternatively list all the free ports within the user port range - but I think dynamic binding is easier and a bit more elegant.

But one way or the other we should be sure to correct the current comment typo (if not through this PR which removes the message entirely) to say `sub-1024` port instead of `sub-1001`.

**Comment by lypht** [comment]
Please rebase

**Comment by scottrigby** [comment]
Added label. Will rebase in roughly an hour

**Comment by scottrigby** [comment]
Rebased

**Comment by scottrigby** [comment]
Rebased again. Also cleaned up a small unused string from #15 in fc8dee2

**Pull request closed without merging**
